services:
  postgres:
    image: postgres:15
    restart: always
    env_file: [.env]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  moodle:
    image: bitnami/moodle:4.4.2
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file: [.env]
    ports:
      - "8080:8080"
    volumes:
      - moodle_app:/bitnami/moodle
      - moodle_data:/bitnami/moodledata
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8080/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20

volumes:
  pgdata:
  moodle_app:
  moodle_data:
